# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorControl', models.IntegerField(max_length=20)),
                ('visitorVariation', models.IntegerField(max_length=20)),
                ('conversionControl', models.IntegerField(max_length=20)),
                ('conversionVariation', models.IntegerField(max_length=20)),
            ],
        ),
    ]
